# Generated by Django 3.2.3 on 2021-08-07 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0003_userprofile_is_dropper'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_location', models.CharField(max_length=150)),
                ('pickup_landmark', models.CharField(max_length=50, null=True)),
                ('pickup_phone_number', models.CharField(max_length=13)),
                ('drop_location', models.CharField(max_length=50)),
                ('drop_landmark', models.CharField(max_length=150, null=True)),
                ('drop_phone_number', models.CharField(max_length=13)),
                ('parcel_category', models.CharField(choices=[('Food', 'Food'), ('Documents', 'Documents'), ('Electronics', 'Electronics'), ('Small_furniture', 'Small_furniture'), ('others', 'others')], default='parcel', max_length=20)),
                ('weight_category', models.CharField(choices=[('under_5kg', 'under_5kg'), ('under_10kg', 'under_10kg'), ('under_20kg', 'under_20kg'), ('under_30kg', 'under_30kg'), ('Above_30kg', 'Above_30kg')], default='10kg', max_length=20)),
                ('size_category', models.CharField(choices=[('fits_in_small_bag', 'fits_in_small_bag'), ('Fits_in_car', 'Fits_in_car'), ('Fit_In_truck', 'Fit_In_truck')], default='50cm', max_length=20)),
                ('payment_method', models.CharField(choices=[('UPI', 'UPI'), ('Net_Banking', 'Net_Banking'), ('Cash_on_delivery', 'Cash_on_delivery')], default='UPI', max_length=20)),
                ('user_of_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_of_order', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
