# Generated by Django 3.2.3 on 2021-08-07 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0004_ordersmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersmodel',
            name='parcel_image',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='dropperprofile',
            name='dropper_authentication_photo',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='dropperprofile',
            name='dropper_driving_liscence_photo',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='dropperprofile',
            name='dropper_profile_photo',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='dropperprofile',
            name='dropper_rc_photo',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_profile_photo',
            field=models.URLField(blank=True),
        ),
    ]
