# Generated by Django 3.2.3 on 2021-08-12 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biddingapi', '0002_auto_20210807_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='email_sent',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='email_sent_time',
        ),
        migrations.DeleteModel(
            name='EmailQueue',
        ),
    ]
